plugins {
    alias(libs.plugins.android.application)
}

def versionFile = file("../latest_version.txt")
def versionString = versionFile.exists() ? versionFile.text.trim() : "1.0"

android {
    namespace 'com.app.minlan'
    compileSdk = 37

    defaultConfig {
        applicationId "com.app.minlan"
        minSdk 29
        targetSdk 36

        // Change version code/name from file ../latest_version.txt
        versionCode versionString.split('\\.')[0].toInteger()
        versionName versionString

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

tasks.register('deploy') {
    dependsOn 'assembleDebug'
    doLast {
        exec {
            commandLine 'adb', 'install', '-r',
                    './build/outputs/apk/debug/app-debug.apk'
        }
        exec {
            commandLine 'adb', 'shell', 'am', 'start',
                    '-n', 'com.app.minlan/.MainActivity'
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.ambilwarna
    implementation 'com.github.iasonasTan:VersionCheckerLib:v2.0.0'
}
